networks:
  hyperlink:
    driver: bridge

services:
  #  mypet:
  #    image: mypet
  #    build:
  #      context: .
  #      dockerfile: MyPet/Dockerfile
  
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - D:\Docker\Prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - D:\Projects\Docker\Grafana:/var/lib/grafana
  
  
  elasticsearch:
    container_name: es-container
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    networks:
      - hyperlink
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - hyperlink
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"


volumes:
  elasticsearch-data:  
      
  
